dist: trusty
sudo: false
language: generic
install:
- python -m pip install --user pygments restructuredtext-lint
script:
- mkdir test
- pushd test
- touch foo bar baz
- ../seqrename --format=f%04d *
- ls f0001 f0002 f0003
- popd
- shellcheck seqrename
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
